Repository hisptz/dhis2-public-portal, pull requests merged in 2025-06, with the labels that each got.

#114 Configuration Importation & Exportation
  .idea/vcs.xml
  apps/manager/i18n/en.pot
  apps/manager/package.json
  apps/manager/src/modules/configuration/index.tsx
  apps/manager/src/shared/components/ConfigurationPage/ConfigurationPage.tsx
  apps/manager/src/shared/components/ConfigurationPage/components/ExportSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/components/ImportSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/components/LogSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/utils/configurationUtils.ts
  apps/manager/src/shared/components/ImportConfiguration.tsx
  apps/manager/src/shared/components/InitialConfigurationSetup.tsx
  apps/manager/src/shared/components/MenuPage/components/MenuList.tsx
  apps/manager/src/shared/components/MenuPage/components/SortMenuItems/SortMenuItems.tsx
  apps/manager/src/shared/components/SideMenu/SideMenu.tsx
  apps/manager/src/shared/components/TemplateCard.tsx
  apps/manager/src/shared/constants/menu.ts
  apps/manager/src/shared/hooks/config.ts
  apps/portal/src/utils/api/http.ts
  package.json
  packages/shared/tsconfig.tsbuildinfo
  yarn.lock
Labels: enhancement

#170 docs(access): Added documentation for configuring DHIS2 Access Settings with Personal Access Token
  apps/docs/docs/configuration/dhis2-access-settings/index.md
  apps/docs/docs/deployment/intro.md
  apps/docs/docs/deployment/portal/index.md
  apps/docs/package.json
  apps/docs/static/img/dhis2-access-settings/PAT_generation.png
  apps/docs/static/img/dhis2-access-settings/generate_new_PAT.png
  apps/docs/static/img/dhis2-access-settings/manage_personal_access_token.png
  apps/docs/static/img/dhis2-access-settings/user_avatar.png
  apps/docs/static/img/dhis2-access-settings/user_management_page.png
  apps/docs/static/img/dhis2-access-settings/user_org_units_set.png
  apps/docs/static/img/dhis2-access-settings/user_role_authorities.png
  apps/docs/static/img/dhis2-access-settings/user_role_basic_details.png
  apps/docs/static/img/dhis2-access-settings/user_role_management_page.png
  apps/docs/static/img/dhis2-access-settings/user_role_selection.png
  yarn.lock
Labels: documentation

#173 Import-Export of documents
  apps/manager/src/shared/components/ConfigurationPage/components/ExportSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/components/ImportSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/components/LogSection.tsx
  apps/manager/src/shared/components/ConfigurationPage/hooks/file.ts
  apps/manager/src/shared/components/ConfigurationPage/utils/configurationUtils.ts
  apps/manager/src/shared/components/ImportConfiguration.tsx
Labels: enhancement

#203 feat(footer-configuration): add configurable background color options for footer
  apps/manager/src/shared/components/appearance/AppearanceConfig/components/FooterConfig.tsx
  apps/manager/src/shared/components/appearance/appearance-config-forms/FooterConfig/FooterConfigForm.tsx
  apps/manager/src/shared/components/appearance/appearance-config-forms/FooterConfig/components/FooterStyleConfig.tsx
  apps/manager/src/shared/constants/defaults/appearance.ts
  apps/portal/src/components/Footer/Footer.tsx
  apps/portal/src/components/Footer/components/FooterLinks.tsx
  apps/portal/src/components/MainLayout.tsx
  packages/shared/src/schemas/appearance/config.ts
  packages/shared/src/utils/colors.ts
Labels: enhancement

#204 fix(ColorPicker): add text input for color value and improve color selection handling
  apps/manager/src/shared/components/appearance/appearance-config-forms/components/ColorPicker.tsx
  apps/manager/src/shared/components/appearance/appearance-config-forms/components/MultiColorPicker/ColorSelectorModal.tsx
  apps/manager/src/shared/components/appearance/appearance-config-forms/components/MultiColorPicker/MultiColorPicker.tsx
Labels: bug

#202 [FIX]: Duplicate app menu items
  apps/manager/src/shared/components/MenuPage/components/MenuItemForm/MenuItemForm.tsx
Labels: bug
